### ISSUE TITLE
USER STORY: Calendar  Add Button

### ISSUE THREAD

**Issue by yokai-san** [yokai-san/My-First-Agile-Project#5]
As a **user** I can **click a button add time/dates of meet ups to my calendar** so that **don't forget or miss upcoming events**

## Acceptance Criteria

* The add button should be just under the time/date
* Once the button is clicked user is prompted to sign into preferred calendar account
* After sign in time/date should be sort automatically 
* After first sign in additional 'add' button click should just automatically add time/date to calendar

## Tasks

- [ ] Update the time/date module view: the calendar design (HTML and CSS) to include
'Add' button
- [ ] Create a Javascript function to add time/date to users calendar
- [ ] Test the functionality
