### ISSUE TITLE
USER STORY: Uploading Pictures

### ISSUE THREAD

**Issue by yokai-san** [yokai-san/My-First-Agile-Project#6]
As a **user** I can **upload pictures I took at a meetup** so that **I can like and comment on other user photos**

## Acceptance Criteria

* Upload function should be provided as a large '+' symbol
* The '+' should have the ability to upload multiple pictures 

## Tasks

- [ ] Update the HTML and CSS to include the
'+' 
- [ ] Add code to allow liking and commenting on photos
- [ ] Test the functionality
